# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 78c799bda9789d24408eaf3fd4e03010f7257ef457acb0f49dadd9562fa97361ec3720b9d25506064bc02b5a63fc311e4e82b1ceb53571a267d065675181c4a0
  mail_pass: noreplyGG2

test:
  domain_name: example.com 
  secret_key_base: 70f2947cdb9c9800b6328ec22b50179eb6a9a685e48d06c26f97f5d2131f08374edccb0893703993a66b3a561515fbca2e320a23e3e7e82d2ccd73339cd25661

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mail_pass: <%= ENV["MAIL_PASS"] %>